export const INITIATE_FETCH_MODULES_MENU = 'INITIATE_FETCH_MODULES_MENU';
export const FETCH_BASIC_MENU = 'FETCH_BASIC_MENU';
export const FETCH_MASTER_MENU = 'FETCH_MASTER_MENU';
export const FETCH_MODULES_MENU = 'FETCH_MODULES_MENU';
export const MENU_PATH_SELECTION = 'MENU_PATH_SELECTION';
export const ROUTE_FINDING = 'ROUTE_FINDING';
export const RESET_TAB_MENU_PROPERTY = 'RESET_TAB_MENU_PROPERTY'

export const INITIATE_FETCH_FORM_CONTROL = 'INITIATE_FETCH_FORM_CONTROL';
export const FETCH_FORM_CONTROL = 'FETCH_FORM_CONTROL';
export const STORE_FORM_CONTROL = 'STORE_FORM_CONTROL';

export const SET_CHIP_DATA = 'SET_CHIP_DATA';
export const ADD_GRID_CONTROL_DATA = 'ADD_GRID_CONTROL_DATA';
export const DELETE_ALL_GRID_CONTROL_DATA = 'DELETE_ALL_GRID_CONTROL_DATA';
export const EDIT_GRID_CONTROL_DATA = 'EDIT_GRID_CONTROL_DATA';
export const DELETE_GRID_CONTROL_DATA = 'DELETE_GRID_CONTROL_DATA';



export const POST_FORM_DATA = 'POST_FORM_DATA';


export const VIEW_REPORT_DATA = 'VIEW_REPORT_DATA';
export const INITIATE_FETCH_REPORT_DATA = 'INITIATE_FETCH_REPORT_DATA';
export const STORE_REPORT_DATA = 'STORE_REPORT_DATA';

