export const INITIATE_FETCH_MODULES_MENU = 'INITIATE_FETCH_MODULES_MENU';
export const FETCH_MODULES_MENU = 'FETCH_MODULES_MENU';
export const MENU_PATH_SELECTION = 'MENU_PATH_SELECTION';
export const ROUTE_FINDING = 'ROUTE_FINDING';


export const INITIATE_FETCH_FORM_CONTROL = 'INITIATE_FETCH_FORM_CONTROL';
export const FETCH_FORM_CONTROL = 'FETCH_FORM_CONTROL';
export const STORE_FORM_CONTROL = 'STORE_FORM_CONTROL';

export const SET_CHIP_DATA = 'SET_CHIP_DATA';

export const VIEW_REPORT_DATA = 'VIEW_REPORT_DATA';
export const INITIATE_FETCH_REPORT_DATA = 'INITIATE_FETCH_REPORT_DATA';
export const STORE_REPORT_DATA = 'STORE_REPORT_DATA';

